### ISSUE TITLE
mkSEER function error 

### ISSUE THREAD

**Issue by berniceyan** [radivot/SEERaBomb#3]
After loading the SEERaBomb package (the one with the radiation / chemotherapy information) and picking the variables/fields, I try to merge using mkSEER. This error code returns: 

Error in .local(x, ...) : 
  Conversion to int failed; line=786; column=149; string='1A   ' 

I've been trying to figure this out, but am unable to. Please help! 

Many thanks.

**Comment by radivot** [comment]
Can you reinstall SEERaBomb from github right now to confirm it is still a problem (seems I fixed something like this recently). If it still fails, can you send me your exact script so I can reproduce the error?

**Comment by berniceyan** [comment]
Just reinstalled from github and it works now! Thank you for your quick response and attention to this matter.
