### ISSUE TITLE
How to get relative risk of "All Sites" of second cancer?

### ISSUE THREAD

**Issue by zhangyz1997** [radivot/SEERaBomb#5]
In the result matrix of MP-SIR session of SEER*Stat, we may get the SIR of all second cancer sites.
![批注 2020-04-09 211924](https://user-images.githubusercontent.com/22343073/78899496-1a25ca00-7aa8-11ea-9cb3-549fbb57ba68.png)
With SEERaBomb I can only get relative risk (including 95%CI) of specific second cancer. Is there a easy way to achieve this using SEERaBomb,  or should I just follow the example 3 which combines data from both sexes and calculate RR and 95%CI in a manual way? Thank you for your help!

**Comment by radivot** [comment]
see the mkExcelDemo.R file here
https://github.com/radivot/SEERaBomb/blob/master/SEERaBomb/inst/docs/papers/attic/leukemia2016/mkExcelDemo.R

**Comment by zhangyz1997** [comment]
> see the mkExcelDemo.R file here
> https://github.com/radivot/SEERaBomb/blob/master/SEERaBomb/inst/docs/papers/attic/leukemia2016/mkExcelDemo.R

I have reviewed the demo file you kindly provided above but I cannot get any hint on how to add up the relative risks from that file or the generated Excel file.
I have read the README.md and it suggests that I can add up all observes and expectations and use following code to get a total confidence interval.
`rr=O/E;rrL=qchisq(.025,2*O)/(2*E);rrU=qchisq(.975,2*O+2)/(2*E)`
Anyway, thanks for your help

**Comment by radivot** [comment]
yes, you need lines like these

DF=bind_rows(pf$DF,pm$DF)
D=DF%>%group_by(int,rad,cancer2)%>%summarize(O=sum(O),E=sum(E),t=mean(t))
D=D%>%mutate(RR=O/E,rrL=qchisq(.025,2*O)/(2*E),rrU=qchisq(.975,2*O+2)/(2*E))


in example 3 here

https://github.com/radivot/SEERaBomb

to pool across things like sex
