### ISSUE TITLE
mkSEER ：'x' must be numeric 

### ISSUE THREAD

**Issue by leeningzzu** [radivot/SEERaBomb#7]
when I run mkSEER(rdf) , it shows that：
> mkSEER(rdf) 
Making population file data.tables
Error in cut.default(race, labels = c("White", "Black", "Other"), breaks = c(1,  : 
  'x' must be numeric
此外: Warning message:
Unknown or uninitialised column: `reg`. 
 
As download the data in ASCII format is no longer an option, I modified the pickFieldsfunction to  analyse SEER_1975_2016_TEXTDATA without Radiation/Chemotherpy Databases.   

If I just need SEER_1975_2016_TEXTDATA without Radiation/Chemotherpy Databases, is there any way to merge all the files? 

Or could you share the Radiation/Chemotherpy Databases (1975-2016) in ASCII format? My access is granted , but after April 15, 2020, access only limited in SEER*Stat's Client-Server mode.

Thanks for your help.

**Comment by radivot** [comment]
Is this using the new release of SEER?  If so, has the new release of the
treatment data come out yet?  SEERaBomb only works with the treatment
dataset.

**Comment by leeningzzu** [comment]
Yes, the 1975-2017 SEER Data was released on April 15, 2020, and the data can only be accessed through SEER*Stat in client-server mode.

**Comment by radivot** [comment]
As stated at the top of the readme here
https://github.com/radivot/SEERaBomb (and
pasted in below), I need the ASCII text version of the treatment data.
Please let me know when that is available. I'll then need several days to
make sure everything works with the new dataset.

WARNING: SEERaBomb does not work with SEER data that does not contain
treatment information, i.e. you must obtain this extended dataset
https://seer.cancer.gov/data/treatment.html by signing an additional SEER
data use agreement.

To set up SEER data use in R, unzip the custom radiation and chemotherapy
ASCII text version of the SEER data into ~/data/SEER where ~ is your home
directory. On a Mac ~ is /Users/username, on linux it is /home/username,
and in Windows ~ is /Users/username/Documents.

**Comment by leeningzzu** [comment]
I'm sorry, the ASCII text version of the treatment data can't be downloaded, it can only be accessed through SEER*Stat in client-server mode,please see https://seer.cancer.gov/data/2020-data-changes.html for the changes with this data release.  That's why I want to modify the pickFields function, I like using R to analyse data, it is a bad new.

**Comment by radivot** [comment]
I would just use the old data for a while and hope that maybe it will come
out later

**Comment by leeningzzu** [comment]
So could you share the Radiation/Chemotherpy Databases (1975-2016) in ASCII format? My access is granted , but after April 15, 2020, access only limited in SEER*Stat's Client-Server mode. I like the SEERaBomb, but I only downloaded the incidence data.
